x-stream-adapter: &stream-adapter
  image: arionstream/stream-adapter:latest
  build: ./services/stream-adapter
  restart: unless-stopped
  expose:
    - 5000

x-stream-processor-a: &stream-processor-a
  image: arionstream/stream-processor-a:latest
  build: ./services/stream-processors/base
  restart: unless-stopped

x-stream-processor-b: &stream-processor-b
  image: arionstream/stream-processor-b:latest
  build: ./services/stream-processors/base
  restart: unless-stopped

volumes:
  broker_data:
  storage_data:

services:
  stream-adapter-1:
    <<: *stream-adapter
    environment:
      - SOURCE_URI=/videos/video.mp4
    volumes:
      - ./videos:/videos

  stream-processor-a1:
    <<: *stream-processor-a
    environment:
      - SENDER_URI=stream-adapter-1:5000
    depends_on:
      - stream-adapter-1

  stream-processor-b1:
    <<: *stream-processor-b
    environment:
      - SENDER_URI=stream-adapter-1:5000
    depends_on:
      - stream-adapter-1

  broker:
    image: arionstream/broker:latest
    build: ./services/broker
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_RABBITMQ_DEFAULT_PASS}
    volumes:
      - broker_data:/var/lib/rabbitmq/

  storage:
    image: arionstream/storage:latest
    build: ./services/storage
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${STORAGE_MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${STORAGE_MINIO_ROOT_PASSWORD}
      - MINIO_REGION_NAME=us-east-1
    volumes:
      - storage_data:/data
