x-depends-on-broker: &depends-on-broker
  broker:
    condition: service_healthy
    restart: true

x-stream-adapter: &stream-adapter
  image: arionstream/stream-adapter:latest
  build: ./services/stream-adapter
  restart: unless-stopped
  expose:
    - 5000
  profiles:
    - all
    - stream-adapters

x-stream-processor-a: &stream-processor-a
  image: arionstream/stream-processor-a:latest
  build: ./services/stream-processors/base
  restart: unless-stopped
  expose:
    - 5000
  profiles:
    - all
    - stream-processors

x-stream-processor-b: &stream-processor-b
  image: arionstream/stream-processor-b:latest
  build: ./services/stream-processors/base
  restart: unless-stopped
  expose:
    - 5000
  profiles:
    - all
    - stream-processors

x-classifier-js-all: &classifier-js-all
  image: arionstream/classifier-js-all:latest
  build: ./services/classifiers/base-js
  restart: unless-stopped
  profiles:
    - all
    - classifiers

x-actuator-js-all: &actuator-js-all
  image: arionstream/actuators-js-all:latest
  build: ./services/actuators/base-js
  restart: unless-stopped
  profiles:
    - all
    - actuators

volumes:
  broker_data:
  storage_data:

services:
  stream-adapter-1:
    <<: *stream-adapter
    environment:
      - SOURCE_URI=/dev/video0 # Can be a video file (/videos/video.mp4), webcam, or external camera
      - LOG_LEVEL=${LOG_LEVEL}
    volumes:
      - ./videos:/videos # Used to access local video files
    devices:
      - /dev/video0:/dev/video0 # Used to access the webcam

  stream-processor-a1:
    <<: *stream-processor-a
    environment:
      - SENDER_URI=stream-adapter-1:5000
      - BROKER_RABBITMQ_CONNECTION_URI=${BROKER_RABBITMQ_CONNECTION_URI}
      - BROKER_RABBITMQ_EXCHANGE_NAME=${BROKER_RABBITMQ_EXCHANGE_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      <<: *depends-on-broker
      stream-adapter-1:
        condition: service_started

  stream-processor-b1:
    <<: *stream-processor-b
    environment:
      - SENDER_URI=stream-adapter-1:5000
      - BROKER_RABBITMQ_CONNECTION_URI=${BROKER_RABBITMQ_CONNECTION_URI}
      - BROKER_RABBITMQ_EXCHANGE_NAME=${BROKER_RABBITMQ_EXCHANGE_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      <<: *depends-on-broker
      stream-adapter-1:
        condition: service_started

  stream-processor-b2:
    <<: *stream-processor-b
    environment:
      - SENDER_URI=stream-processor-b1:5000
      - BROKER_RABBITMQ_CONNECTION_URI=${BROKER_RABBITMQ_CONNECTION_URI}
      - BROKER_RABBITMQ_EXCHANGE_NAME=${BROKER_RABBITMQ_EXCHANGE_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      <<: *depends-on-broker
      stream-processor-b1:
        condition: service_started

  classifier-js-all-1:
    <<: *classifier-js-all
    environment:
      - BROKER_RABBITMQ_CONNECTION_URI=${BROKER_RABBITMQ_CONNECTION_URI}
      - BROKER_RABBITMQ_EXCHANGE_NAME=${BROKER_RABBITMQ_EXCHANGE_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      <<: *depends-on-broker

  actuator-js-all-1:
    <<: *actuator-js-all
    environment:
      - BROKER_RABBITMQ_CONNECTION_URI=${BROKER_RABBITMQ_CONNECTION_URI}
      - BROKER_RABBITMQ_EXCHANGE_NAME=${BROKER_RABBITMQ_EXCHANGE_NAME}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      <<: *depends-on-broker

  broker:
    image: arionstream/broker:latest
    build: ./services/broker
    restart: unless-stopped
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${BROKER_RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${BROKER_RABBITMQ_DEFAULT_PASS}
    volumes:
      - broker_data:/var/lib/rabbitmq/
    profiles:
      - all
      - broker

  storage:
    image: arionstream/storage:latest
    build: ./services/storage
    restart: unless-stopped
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=${STORAGE_MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${STORAGE_MINIO_ROOT_PASSWORD}
      - MINIO_REGION_NAME=us-east-1
    volumes:
      - storage_data:/data
    profiles:
      - storage
